name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create-release: # Переименовали job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build fat JAR
        run: ./gradlew clean shadowJar --no-daemon --console=plain

      - name: Verify JAR exists
        run: |
          echo "Listing files in build/libs:"
          ls -l build/libs/
          if [ ! -f "build/libs/vpn-bot-telegram-1.0-SNAPSHOT-all.jar" ]; then
            echo "Error: JAR file not found!"
            exit 1
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/libs/vpn-bot-telegram-1.0-SNAPSHOT-all.jar