name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build fat JAR
        run: ./gradlew clean shadowJar --no-daemon --console=plain

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/libs/vpn-bot-telegram-1.0-SNAPSHOT-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
